# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = swww-daemon &
exec-once = waybar &
# exec-once = qs -c noctalia-shell
exec-once = ./scripts/xdg-desktop-portal-hyprland.sh
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = udiskie
exec-once = elephant &
exec-once = walker --gapplication-service &
# exec-once = ./scripts/connect-bt.sh
exec-once = bluetoothctl trust 84:AC:60:60:E2:C6
exec-once = bluetoothctl power on
exec-once = bluetoothctl connect 84:AC:60:60:E2:C6
# exec-once = hyprpaper
# exec-once = mpvpaper '*' ~/Pictures/wall.mp4
